### 1. Import Libraries

In [3]:
import pandas as pd
from mazajak_api import predict

negative
positive
['negative', 'positive']

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', lambda x: '%.5f' % x)

### 2. Read the Data and Classify it

In [5]:
tweets = pd.read_csv('Tweets\\final_tweets_cleaned.csv')
tweets.columns

Index(['Unnamed: 0', 'ID', 'Tweet', 'Timestamp', 'Likes', 'Retweets', 'Length',
       'Date', 'Time'],
      dtype='object')

In [6]:
tweets = tweets.drop(['Unnamed: 0'], axis=1)

In [7]:
display(tweets.head())
display(tweets.tail())

,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time
0,1497300372569739264,قبيل الاحتفال بـ اليوم الدولي لمراة تستعد كوكبة الفنانات الاستثناءيات وفرق موسيقية بقيادات نساءية لابهار زوار اكسبو دبي عينك علا اكسبو,2022-02-25 20:00:01+00:00,1,0,198,2022-02-25,20:00:01
1,1497299670522994691,لحظات نزول دابانغ سلمان خان علا ارض المسرح اكسبو يقف علا مجسم لجناحي صقر والتصفيق مستمر الجمهور,2022-02-25 19:57:14+00:00,2,0,207,2022-02-25,19:57:14
2,1497297255245754371,ليلة ميزة بانتظارنا الحانها شرقية نجومها استثناءين اكسبو,2022-02-25 19:47:38+00:00,0,0,232,2022-02-25,19:47:38
3,1497295489481510914,اصدق حفلة احلا فستان مستان انا بختار واذا حفلة فبختار حفلة حفلات نانسي كلون حلوين يعني,2022-02-25 19:40:37+00:00,3,1,168,2022-02-25,19:40:37
4,1497290589800480779,جنون بعده جنون دابانغ سلمان خان يستعرض حشد كبير معجبينه اكسبو,2022-02-25 19:21:09+00:00,5,2,178,2022-02-25,19:21:09

,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time
7970,1510697936317030406,اغلق معرض اكسبو الامارات اجلته الجاءحة ابوابه الترقب وسبعة مليارات الاستثمارات و ساعة العمل وستة اشهر الاحتفالات الحدث الارث الحقيقي متوقعا الاجابة عبر السلسلة,2022-04-03 19:17:10+00:00,9,1,279,2022-04-03,19:17:10
7971,1510688181640962050,اختام معرض اكسبو دبي يومين الخميس فرصة المعرض فترة سرني شاهدته حسن تنظيم وتظاهره عالمية ناجحة نبارك لدولة الامارات الشقيقة النجاح المتفرد وباذن اله نامل استضافة معرض اكسبو الدولي الرياض تحقيق رءية السعودية تصويري,2022-04-03 18:38:24+00:00,1,0,304,2022-04-03,18:38:24
7972,1510686349417984006,هاشتاق عربي انتهاءه الامارات تكشف عد زوار اكسبو دبي,2022-04-03 18:31:07+00:00,0,0,112,2022-04-03,18:31:07
7973,1510686265649340420,الحمدله انجاز راءع شكرا الامارات الحبيبه نبارك نجاح اكسبو دبي ونجاح جناح السعودية في اكسبو ونءكد نجاح الامارات نجاحنا,2022-04-03 18:30:47+00:00,0,2,160,2022-04-03,18:30:47
7974,1510686095054356487,اكسبو ابرز الارقام القياسية حقها جناح السعودية اكسبو دبي,2022-04-03 18:30:06+00:00,0,0,100,2022-04-03,18:30:06

In [8]:
# Test run 
tweet = 'كيفك'
print(predict(tweet))

tweets.shape[0]

positive

7975

In [12]:
tweets.isna().sum()

ID           0
Tweet        1
Timestamp    0
Likes        0
Retweets     0
Length       0
Date         0
Time         0
dtype: int64

In [15]:
tweets = tweets.dropna(subset=['Tweet'])

In [23]:
size = 50
chunks = [tweets[i:i+size].copy() for i in range(0, tweets.shape[0], size)]

In [24]:
no_chunks = len(chunks)
no_chunks

160

In [25]:
for i in range(0, no_chunks):
    # chunks[i]['Class'] = chunks[i]['Tweet'].apply(lambda x: predict(x))
    chunks[i]['Class'] = chunks[i]['Tweet'].map(predict)
    print(f'__________ lap {i+1} of {no_chunks} __________')

__________ lap 1 of 160 __________
__________ lap 2 of 160 __________
__________ lap 3 of 160 __________
__________ lap 4 of 160 __________
__________ lap 5 of 160 __________
__________ lap 6 of 160 __________
__________ lap 7 of 160 __________
__________ lap 8 of 160 __________
__________ lap 9 of 160 __________
__________ lap 10 of 160 __________
__________ lap 11 of 160 __________
__________ lap 12 of 160 __________
__________ lap 13 of 160 __________
__________ lap 14 of 160 __________
__________ lap 15 of 160 __________
__________ lap 16 of 160 __________
__________ lap 17 of 160 __________
__________ lap 18 of 160 __________
__________ lap 19 of 160 __________
__________ lap 20 of 160 __________
__________ lap 21 of 160 __________
__________ lap 22 of 160 __________
__________ lap 23 of 160 __________
__________ lap 24 of 160 __________
__________ lap 25 of 160 __________
__________ lap 26 of 160 __________
__________ lap 27 of 160 __________
__________ lap 28 of 160 __________
__________ lap 29 of 160 __________
__________ lap 30 of 160 __________
__________ lap 31 of 160 __________
__________ lap 32 of 160 __________
__________ lap 33 of 160 __________
__________ lap 34 of 160 __________
__________ lap 35 of 160 __________
__________ lap 36 of 160 __________
__________ lap 37 of 160 __________
__________ lap 38 of 160 __________
__________ lap 39 of 160 __________
__________ lap 40 of 160 __________
__________ lap 41 of 160 __________
__________ lap 42 of 160 __________
__________ lap 43 of 160 __________
__________ lap 44 of 160 __________
__________ lap 45 of 160 __________
__________ lap 46 of 160 __________
__________ lap 47 of 160 __________
__________ lap 48 of 160 __________
__________ lap 49 of 160 __________
__________ lap 50 of 160 __________
__________ lap 51 of 160 __________
__________ lap 52 of 160 __________
__________ lap 53 of 160 __________
__________ lap 54 of 160 __________
__________ lap 55 of 160 __________
__________ lap 56 of 160 __________
__________ lap 57 of 160 __________
__________ lap 58 of 160 __________
__________ lap 59 of 160 __________
__________ lap 60 of 160 __________
__________ lap 61 of 160 __________
__________ lap 62 of 160 __________
__________ lap 63 of 160 __________
__________ lap 64 of 160 __________
__________ lap 65 of 160 __________
__________ lap 66 of 160 __________
__________ lap 67 of 160 __________
__________ lap 68 of 160 __________
__________ lap 69 of 160 __________
__________ lap 70 of 160 __________
__________ lap 71 of 160 __________
__________ lap 72 of 160 __________
__________ lap 73 of 160 __________
__________ lap 74 of 160 __________
__________ lap 75 of 160 __________
__________ lap 76 of 160 __________
__________ lap 77 of 160 __________
__________ lap 78 of 160 __________
__________ lap 79 of 160 __________
__________ lap 80 of 160 __________
__________ lap 81 of 160 __________
__________ lap 82 of 160 __________
__________ lap 83 of 160 __________
__________ lap 84 of 160 __________
__________ lap 85 of 160 __________
__________ lap 86 of 160 __________
__________ lap 87 of 160 __________
__________ lap 88 of 160 __________
__________ lap 89 of 160 __________
__________ lap 90 of 160 __________
__________ lap 91 of 160 __________
__________ lap 92 of 160 __________
__________ lap 93 of 160 __________
__________ lap 94 of 160 __________
__________ lap 95 of 160 __________
__________ lap 96 of 160 __________
__________ lap 97 of 160 __________
__________ lap 98 of 160 __________
__________ lap 99 of 160 __________
__________ lap 100 of 160 __________
__________ lap 101 of 160 __________
__________ lap 102 of 160 __________
__________ lap 103 of 160 __________
__________ lap 104 of 160 __________
__________ lap 105 of 160 __________
__________ lap 106 of 160 __________
__________ lap 107 of 160 __________
__________ lap 108 of 160 __________
__________ lap 109 of 160 __________
__________ lap 110 of 160 __________
__________ lap 111 of 160 __________
__________ lap 112 of 160 __________
__________ lap 113 of 160 __________
__________ lap 114 of 160 __________
__________ lap 115 of 160 __________
__________ lap 116 of 160 __________
__________ lap 117 of 160 __________
__________ lap 118 of 160 __________
__________ lap 119 of 160 __________
__________ lap 120 of 160 __________
__________ lap 121 of 160 __________
__________ lap 122 of 160 __________
__________ lap 123 of 160 __________
__________ lap 124 of 160 __________
__________ lap 125 of 160 __________
__________ lap 126 of 160 __________
__________ lap 127 of 160 __________
__________ lap 128 of 160 __________
__________ lap 129 of 160 __________
__________ lap 130 of 160 __________
__________ lap 131 of 160 __________
__________ lap 132 of 160 __________
__________ lap 133 of 160 __________
__________ lap 134 of 160 __________
__________ lap 135 of 160 __________
__________ lap 136 of 160 __________
__________ lap 137 of 160 __________
__________ lap 138 of 160 __________
__________ lap 139 of 160 __________
__________ lap 140 of 160 __________
__________ lap 141 of 160 __________
__________ lap 142 of 160 __________
__________ lap 143 of 160 __________
__________ lap 144 of 160 __________
__________ lap 145 of 160 __________
__________ lap 146 of 160 __________
__________ lap 147 of 160 __________
__________ lap 148 of 160 __________
__________ lap 149 of 160 __________
__________ lap 150 of 160 __________
__________ lap 151 of 160 __________
__________ lap 152 of 160 __________
__________ lap 153 of 160 __________
__________ lap 154 of 160 __________
__________ lap 155 of 160 __________
__________ lap 156 of 160 __________
__________ lap 157 of 160 __________
__________ lap 158 of 160 __________
__________ lap 159 of 160 __________
__________ lap 160 of 160 __________

,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time,Class
7970,1510697936317030406,اغلق معرض اكسبو الامارات اجلته الجاءحة ابوابه الترقب وسبعة مليارات الاستثمارات و ساعة العمل وستة اشهر الاحتفالات الحدث الارث الحقيقي متوقعا الاجابة عبر السلسلة,2022-04-03 19:17:10+00:00,9,1,279,2022-04-03,19:17:10,neutral
7971,1510688181640962050,اختام معرض اكسبو دبي يومين الخميس فرصة المعرض فترة سرني شاهدته حسن تنظيم وتظاهره عالمية ناجحة نبارك لدولة الامارات الشقيقة النجاح المتفرد وباذن اله نامل استضافة معرض اكسبو الدولي الرياض تحقيق رءية السعودية تصويري,2022-04-03 18:38:24+00:00,1,0,304,2022-04-03,18:38:24,positive
7972,1510686349417984006,هاشتاق عربي انتهاءه الامارات تكشف عد زوار اكسبو دبي,2022-04-03 18:31:07+00:00,0,0,112,2022-04-03,18:31:07,neutral
7973,1510686265649340420,الحمدله انجاز راءع شكرا الامارات الحبيبه نبارك نجاح اكسبو دبي ونجاح جناح السعودية في اكسبو ونءكد نجاح الامارات نجاحنا,2022-04-03 18:30:47+00:00,0,2,160,2022-04-03,18:30:47,positive
7974,1510686095054356487,اكسبو ابرز الارقام القياسية حقها جناح السعودية اكسبو دبي,2022-04-03 18:30:06+00:00,0,0,100,2022-04-03,18:30:06,positive

### 3. Store the Classified Data

In [30]:
tweets = pd.concat(chunks)

In [31]:
display(tweets.head())
display(tweets.tail())

,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time,Class
0,1497300372569739264,قبيل الاحتفال بـ اليوم الدولي لمراة تستعد كوكبة الفنانات الاستثناءيات وفرق موسيقية بقيادات نساءية لابهار زوار اكسبو دبي عينك علا اكسبو,2022-02-25 20:00:01+00:00,1,0,198,2022-02-25,20:00:01,positive
1,1497299670522994691,لحظات نزول دابانغ سلمان خان علا ارض المسرح اكسبو يقف علا مجسم لجناحي صقر والتصفيق مستمر الجمهور,2022-02-25 19:57:14+00:00,2,0,207,2022-02-25,19:57:14,positive
2,1497297255245754371,ليلة ميزة بانتظارنا الحانها شرقية نجومها استثناءين اكسبو,2022-02-25 19:47:38+00:00,0,0,232,2022-02-25,19:47:38,positive
3,1497295489481510914,اصدق حفلة احلا فستان مستان انا بختار واذا حفلة فبختار حفلة حفلات نانسي كلون حلوين يعني,2022-02-25 19:40:37+00:00,3,1,168,2022-02-25,19:40:37,positive
4,1497290589800480779,جنون بعده جنون دابانغ سلمان خان يستعرض حشد كبير معجبينه اكسبو,2022-02-25 19:21:09+00:00,5,2,178,2022-02-25,19:21:09,positive

,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time,Class
7970,1510697936317030406,اغلق معرض اكسبو الامارات اجلته الجاءحة ابوابه الترقب وسبعة مليارات الاستثمارات و ساعة العمل وستة اشهر الاحتفالات الحدث الارث الحقيقي متوقعا الاجابة عبر السلسلة,2022-04-03 19:17:10+00:00,9,1,279,2022-04-03,19:17:10,neutral
7971,1510688181640962050,اختام معرض اكسبو دبي يومين الخميس فرصة المعرض فترة سرني شاهدته حسن تنظيم وتظاهره عالمية ناجحة نبارك لدولة الامارات الشقيقة النجاح المتفرد وباذن اله نامل استضافة معرض اكسبو الدولي الرياض تحقيق رءية السعودية تصويري,2022-04-03 18:38:24+00:00,1,0,304,2022-04-03,18:38:24,positive
7972,1510686349417984006,هاشتاق عربي انتهاءه الامارات تكشف عد زوار اكسبو دبي,2022-04-03 18:31:07+00:00,0,0,112,2022-04-03,18:31:07,neutral
7973,1510686265649340420,الحمدله انجاز راءع شكرا الامارات الحبيبه نبارك نجاح اكسبو دبي ونجاح جناح السعودية في اكسبو ونءكد نجاح الامارات نجاحنا,2022-04-03 18:30:47+00:00,0,2,160,2022-04-03,18:30:47,positive
7974,1510686095054356487,اكسبو ابرز الارقام القياسية حقها جناح السعودية اكسبو دبي,2022-04-03 18:30:06+00:00,0,0,100,2022-04-03,18:30:06,positive

In [32]:
tweets = tweets.reset_index()

In [33]:
display(tweets.tail())

,index,ID,Tweet,Timestamp,Likes,Retweets,Length,Date,Time,Class
7969,7970,1510697936317030406,اغلق معرض اكسبو الامارات اجلته الجاءحة ابوابه الترقب وسبعة مليارات الاستثمارات و ساعة العمل وستة اشهر الاحتفالات الحدث الارث الحقيقي متوقعا الاجابة عبر السلسلة,2022-04-03 19:17:10+00:00,9,1,279,2022-04-03,19:17:10,neutral
7970,7971,1510688181640962050,اختام معرض اكسبو دبي يومين الخميس فرصة المعرض فترة سرني شاهدته حسن تنظيم وتظاهره عالمية ناجحة نبارك لدولة الامارات الشقيقة النجاح المتفرد وباذن اله نامل استضافة معرض اكسبو الدولي الرياض تحقيق رءية السعودية تصويري,2022-04-03 18:38:24+00:00,1,0,304,2022-04-03,18:38:24,positive
7971,7972,1510686349417984006,هاشتاق عربي انتهاءه الامارات تكشف عد زوار اكسبو دبي,2022-04-03 18:31:07+00:00,0,0,112,2022-04-03,18:31:07,neutral
7972,7973,1510686265649340420,الحمدله انجاز راءع شكرا الامارات الحبيبه نبارك نجاح اكسبو دبي ونجاح جناح السعودية في اكسبو ونءكد نجاح الامارات نجاحنا,2022-04-03 18:30:47+00:00,0,2,160,2022-04-03,18:30:47,positive
7973,7974,1510686095054356487,اكسبو ابرز الارقام القياسية حقها جناح السعودية اكسبو دبي,2022-04-03 18:30:06+00:00,0,0,100,2022-04-03,18:30:06,positive

In [34]:
tweets.isna().sum()

index        0
ID           0
Tweet        0
Timestamp    0
Likes        0
Retweets     0
Length       0
Date         0
Time         0
Class        0
dtype: int64

In [35]:
tweets.to_csv('Tweets\\tweets_classified.csv')